### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by joseantgv** [ataft/plugin-image-zoom#4]
I get this error

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ataft/plugin-image-zoom'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose npm-session 74a68d5a544baeb4
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for github:ataft/plugin-image-zoom Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t ssh://git@github.com/ataft/plugin-image-zoom.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 2ms
9 timing stage:runTopLevelLifecycles Completed in 4059ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
10 verbose stack     at onErrorNT (internal/child_process.js:467:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
11 verbose cwd C:\wamp64\www\docusaurus\docs
12 verbose Windows_NT 10.0.19042
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ataft/plugin-image-zoom"
14 verbose node v14.17.0
15 verbose npm  v6.14.13
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno -4058
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t ssh://git@github.com/ataft/plugin-image-zoom.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ -4058, true ]
```

when I execute `npm install ataft/plugin-image-zoom`

**Comment by joseantgv** [comment]
Git client was not installed.
